name: "90 - ==============="

on:
  workflow_call:

permissions: {}

jobs:
  display-only:
    if: ${{ false }}
    runs-on: ubuntu-latest

    steps:
      - name: Display-only placeholder
        run: echo "This workflow must never run."
